# Generated by Django 6.1.1 on 2026-09-24 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prueba', '0002_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pais_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prueba.pais'),
        ),
    ]
