# Generated by Django 6.1.1 on 2026-09-26 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_alter_producto_options_alter_producto_precio_costo_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='producto',
            name='producto_stock_no_negativo',
        ),
    ]
