# Generated by Django 6.1.1 on 2026-09-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_remove_producto_producto_stock_no_negativo'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='producto_stock_no_negativo'),
        ),
    ]
